//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Doanhthu : XPObject
    {
        Hoadon fMaHD;
        [Association(@"DoanhthuReferencesHoadon")]
        public Hoadon MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<Hoadon>(nameof(MaHD), ref fMaHD, value); }
        }
        DateTime fNgay;
        public DateTime Ngay
        {
            get
            {
                if (MaHD != null)
                {
                    fNgay = MaHD.Ngaytao;
                }
                return fNgay;
            }
        }
        decimal fTong;
        public decimal Tong
        {
            get
            {
                if (MaHD != null)
                {
                    fTong = MaHD.HoadonCTs.Sum(ct => ct.Thanhtien);
                }
                return fTong;
            }
            
        }
    }

}
