//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class HoadonCT : XPObject
    {
        Hoadon fMaHDCT;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon MaHDCT
        {
            get { return fMaHDCT; }
            set { SetPropertyValue<Hoadon>(nameof(MaHDCT), ref fMaHDCT, value); }
        }
        Menu fMasanpham;
        [Association(@"HoadonCTReferencesMenu")]
        public Menu Masanpham
        {
            get { return fMasanpham; }
            set { SetPropertyValue<Menu>(nameof(Masanpham), ref fMasanpham, value); }
        }
        string fTensanpham;
        public string Tensanpham
        {
            get
            {
                if (Masanpham != null)
                {
                    fTensanpham = Masanpham.Tensanpham;
                }
                return fTensanpham;
            }
        }
        short fSoluong;
        public short Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<short>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fThanhtien;
        public decimal Thanhtien
        {
            get 
            { 
                if(Masanpham != null)
                {
                    fThanhtien = (decimal)Soluong * Masanpham.Giatien;
                }
                return fThanhtien; 
            }
            
        }
    }

}
