//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class TrangthaiTT : XPObject
    {
        string fMatrangthaiTT;
        public string MatrangthaiTT
        {
            get { return fMatrangthaiTT; }
            set { SetPropertyValue<string>(nameof(MatrangthaiTT), ref fMatrangthaiTT, value); }
        }
        string fTentrangthaiTT;
        public string TentrangthaiTT
        {
            get { return fTentrangthaiTT; }
            set { SetPropertyValue<string>(nameof(TentrangthaiTT), ref fTentrangthaiTT, value); }
        }
        [Association(@"ThanhtoanReferencesTrangthaiTT")]
        public XPCollection<Thanhtoan> Thanhtoans { get { return GetCollection<Thanhtoan>(nameof(Thanhtoans)); } }
    }

}
